<?php

use App\Models\User;
use App\Models\Photo;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return '<center style="background:green; margin:50px 0; border-radius:34px;  color:honeydew; padding:12rem;">
    <h1>Hello From Laravel 9.</h1>
    <h3>Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.</h3>

    </center>';
});

// Route::get('/about', function () {
//     return 'This is <b>ABOUT</b> Page';
// });

// Route::get('/contact', function () {
//     return 'This is <b>CONTACT</b> Page';
// });

// Route::get('/posts/{id}/{name}', function($id,$name){
//    return  "This is post number " . $id . " which is created by ".$name;
// });
// Route::get('admin/posts/example',array('as'=>'admin.home',function(){
//     $url = route('admin.home');

//     return "This URL is " . $url;
// }));

// Route::get('/post/{name}/{id}', [PostsController::class, 'index'])->name('index');
// Route::get('/about', [PostsController::class, 'about'])->name('about');
// Route::get('/show/{id}/{name}/{password}', [PostsController::class, 'showPosts'])->name('show');
// Route::get('/contact', [PostsController::class, 'contact'])->name('contact');

/*
------------------------
Database Raw SQL Queries
------------------------
 */

// Route::get('/insert', function () {
//     DB::insert('insert into posts (title, content) values (?, ?)', ['Eloquent ORM', 'firstOrFail() returns the first record found in the database. If no matching model exist, it throws an error.']);
// });

// Route::get('/read', function () {
//     $results = DB::select('select * from posts where id = ?', [4]);
//     return var_dump($results);
// });

// //    foreach($results as $post){
// //     // return $post->title;
// //    }

// });

// Route::get('/update', function(){

//     $updated = DB::update('update posts set title = "PHP with Laravel" where id =?', [1]);

//     return $updated;
// });

// Route::get('/delete', function(){
//     $deleted = DB::delete('delete from posts where id = ?',[3]);
//     return $deleted;
// });

// Route::resource('post/{name}/{id}', PostsController::class);

/*
===================
Read, Update, Create, Delete Data
===================
 */

// Route::get('/read', function () {

//     $posts = Post::all();

//     foreach ($posts as $post) {

//         return $post;
//     }

// });

// Route::get('/find', function () {

//     $posts = Post::find(1);

//     return $posts->title;

// });

// Route::get('/findwhere', function () {
//     $posts = Post::where('id', 1)->orderBy('id', 'desc')->take(1)->get();
//     return $posts;
// });

// Route::get('/findmore', function () {
//     // $posts = Post::findOrFail(1);
//     // return $posts;

//     $posts = Post::where('title', '<', 50)->firstOrFail();
//     return $posts;
// });

/*
===================
ELOQUENT Inserting Saving Data
===================
 */

// Route::get('/basicinsert', function () {
//     $post = new Post;

//     $post->title = 'New Eloquent title insert';
//     $post->content = 'WOW! Eloquent is really cool';

//     $post->save();
// });

// Route::get('/basicupdate2', function(){
//     $post = Post::find(2);

//     $post->title = '2New Eloquent title insert2';
//     $post->content = 'WOW! 2Eloquent is really cool2';

// $post->save();

// });

// Route::get('/create', function () {
//     Post::create(['title' => 'Index Lengths & MySQL / MariaDB', 'content' => 'By default, Laravel uses the utf8mb4 character set. If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 release, you may need to manually configure the default string length generated by migrations in order for MySQL to create indexes for them.']);
// });

// Route::get('/update', function () {

//     Post::where('id', 3)->where('is_admin', 0)->update(['title' => 'Laravel Updated title', 'content' => 'I love to learn Laravel']);
// });

// Route::get('/delete', function () {

//     $post = Post::find(2);

//     $post->delete();
// });

// Route::get('/delete2', function(){
//    Post::destroy(5,6);
// });

// Route::get('/softdelete', function () {
//     Post::find(4)->delete();
// });

// Route::get('/readsoftdelete', function () {

// $post = Post::find(5);
// return $post;

//    $post = Post::withTrashed()->where('id', 4)->get();
//     return $post;

//     $post = POST::onlyTrashed()->orderBy('deleted_at', 'desc')->get();

//     return $post;
// });

// Route::get('/restore', function () {
//     Post::withTrashed()->where('is_admin', 1)->restore();
// });

// Route::get('/forcedelete', function () {

//     Post::withTrashed()->where('is_admin', 0)->forceDelete();
// });

// Route::get('/forcedelete2', function () {

//     Post::onlyTrashed()->where('is_admin', 0)->forceDelete();
// });

/*
======================
ELOQUENT RelationShips
======================
 */

//------------
//one to one
//------------

// Route::get('/user/{id}/post', function ($id) {

//     return User::find($id)->post->content;

// });

//INVERSE

// Route::get('/post/{id}/user', function ($id) {

//     return Post::find($id)->user->name;

// });

//------------
//one to many
//------------

// Route::get('/posts', function () {
//     $user = User::find(1);

//     foreach ($user->posts as $post) {
//         echo $post->title . "<br>";
//     }
// });

// Route::get('/user/{id}/role', function ($id) {

//     $user = User::find($id)->roles()->orderBy('id', 'desc')->get();

//     return $user;

// foreach ($user->roles as $role) {
//     return $role->name;
// }
// });

// Route::get('/user/pivot', function () {

//     $user = User::find(1);
//     foreach ($user->roles as $role) {
//         echo $role->pivot->created_at;
//     }

// });

// Route::get('/user/country', function () {
//     $country = Country::find(3);
//     foreach ($country->posts as $post) {
//         return $post->title;
//     }
// });

//===============================
//    Polymorphic Relationship
//===============================

// Route::get('/user/{id}/photos', function ($id) {
//     $post = Post::find($id);

//     foreach ($post->photos as $photo) {
//         return $photo;
//     }
// });

Route::get('/photo/{id}/post', function ($id) {
    $photo = Photo::findOrFail($id);

    return $photo->imageable;
});